name: NodeJS with Webpack

on:
  push:
    branches: [wzrabbit-extra]
  # schedule:
  #   - cron: '*/5 * * * *' 5분마다 자동 갱신 (실험할 때 사용할 것)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build-step2

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: wzrabbit-build
