name: NodeJS with Webpack

on:
  push:
    branches: ["wzrabbit-extra"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3

    # node.js 를 사용합니다.
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm ci
    - run: npm run build-step2
    
    # publish_dir에 들어있는 파일들을 gh-pages 브랜치에 올려줍니다.
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: wzrabbit-build
